[package]
name = "roc_sim"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# randoms
rand = "0.8.5"
rand_xoshiro = "0.6.0"
